### PR TITLE
doc authorizers as requested

### PR DESCRIPTION
**Pull request by stevebuik**

### CODE REVIEW

**Comment by FieryCod** [comment]
@stevebuik I think we can expand the doc a little bit. HL should support not only the authorizers but all the output formats the regular runtime supports.

**Comment by stevebuik** [comment]
ok. I'm not familiar with any other outputs. what did you have in mind?

**Comment by FieryCod** [comment]
For instance step functions should work just fine with HL.

**Comment by stevebuik** [comment]
ok. have you tested step functions? if not, do you want it in the docs yet?

I can change it to a list (with a single) entry but maybe we should wait till someone tests step fns

**Comment by FieryCod** [comment]
@stevebuik I have not tested step-functions yet, but I'm pretty sure they will work. I don't want now to put on you the responsibility in the situation when step-functions won't work. I will accept the PR and test step-functions myself in few weeks :) Thank you for your contribution!

**Pull request merged**
