### PR TITLE
remove 'choly'

### PR DESCRIPTION
**Pull request by ekoontz**

### CODE REVIEW

**Comment by FieryCod** [comment]
@ekoontz regarding docker image I would strongly recommend to change all the invocations to`$GRAALVM/native-image` instead. You can install graalvm using `make install-graalvm` command from this commit: https://github.com/FieryCod/holy-lambda/commit/18b56e36fbe474d168e174f85cddcccf3e0dfc46

**Comment by ekoontz** [comment]
> @ekoontz regarding docker image I would strongly recommend to change all the invocations to`$GRAALVM/native-image` instead. You can install graalvm using `make install-graalvm` command from this commit: [18b56e3](https://github.com/FieryCod/holy-lambda/commit/18b56e36fbe474d168e174f85cddcccf3e0dfc46)

Thanks for that. In `hello-lambda`'s, I changed the Makefile to use the local graalvm on Linux, but I am on MacOS, so I have to keep using the Docker image.

**Comment by FieryCod** [comment]
@ekoontz Great changes so far. I've bumped docker image to latest GraalVM 20.3.0 CE. Thank you for your contribution!

**Comment by ekoontz** [comment]
@FieryCod I removed uses of `choly` from `examples/sqs-example`, but unlike `examples/hello-lambda` I couldn't test it. It seems to require some environment setup, but I couldn't get this to work because the `choly envs` command doesn't work:

```
❯ git log -1
commit 8cf7782acec2f78daf5127ca11d06ce4cdccf333 (HEAD -> master, origin/master, origin/HEAD)
Author: Karol Wójcik <karol.wojcik@tuta.io>
Date:   Sun Dec 20 10:32:14 2020 +0100

    Revert removal of Dockerfile. Bump graalvm

holy-lambda/examples/sqs-example on  master [$?] on ☁️  eu-central-1
❯ pwd
/Users/ekoontz/holy-lambda/examples/sqs-example

holy-lambda/examples/sqs-example on  master [$?] on ☁️  eu-central-1
❯ choly envs
Traceback (most recent call last):
  File "/usr/local/bin/choly", line 33, in <module>
    sys.exit(load_entry_point('choly==0.0.3', 'console_scripts', 'choly')())
  File "/usr/local/lib/python3.9/site-packages/choly-0.0.3-py3.9.egg/choly/__main__.py", line 18, in main
  File "/usr/local/lib/python3.9/site-packages/click-8.0.0a1-py3.9.egg/click/core.py", line 1025, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click-8.0.0a1-py3.9.egg/click/core.py", line 955, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click-8.0.0a1-py3.9.egg/click/core.py", line 1517, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click-8.0.0a1-py3.9.egg/click/core.py", line 1279, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click-8.0.0a1-py3.9.egg/click/core.py", line 710, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/choly-0.0.3-py3.9.egg/choly/commands/envs.py", line 57, in envs
  File "/usr/local/lib/python3.9/site-packages/choly-0.0.3-py3.9.egg/choly/logic/envs.py", line 58, in gen_envs
  File "/usr/local/lib/python3.9/site-packages/choly-0.0.3-py3.9.egg/choly/logic/envs.py", line 27, in gen_aws_sam_envs_file
  File "/usr/local/lib/python3.9/site-packages/choly-0.0.3-py3.9.egg/choly/logic/shared.py", line 17, in get_fns_definitions
  File "/usr/local/lib/python3.9/site-packages/cfn_flip-1.2.3-py3.9.egg/cfn_flip/__init__.py", line 55, in to_json
    data, _ = load(template)
  File "/usr/local/lib/python3.9/site-packages/cfn_flip-1.2.3-py3.9.egg/cfn_flip/__init__.py", line 27, in load
    data = load_json(template)
  File "/usr/local/lib/python3.9/site-packages/cfn_flip-1.2.3-py3.9.egg/cfn_tools/__init__.py", line 20, in load_json
    return json.loads(source, object_pairs_hook=ODict)
  File "/usr/local/Cellar/python@3.9/3.9.0_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not TextIOWrapper

holy-lambda/examples/sqs-example on  master [$?] on ☁️  eu-central-1
❯
```

**Comment by FieryCod** [comment]
It fails on last step which is generating `sam-envs.json`. Ignore it and just add `sam-envs.json` by hand.

sam-envs.json:
```    
{"ReceiveStringLambda": {
    "AWS_ACCESS_KEY": "your-id",
    "AWS_SECRET_KEY": "your-key",
    "CONCATENATED_HOLY_SQS_URL": "url-to-real-sqs"}
```

Idea of this example was to check whether publishing & receiving events works as expected. On my local branch there was another lambda which was listening to api event and then forwarding the message to sqs. Unfortunately the example did not work correctly due to this issue https://github.com/oracle/graal/issues/1387

If you don't mind I can jump straight into the code and fix the example :)

**Comment by ekoontz** [comment]
@FieryCod - sure, please go ahead! 👍

**Review by FieryCod — APPROVED** [review]
Regarding documentation, we will tackle it in one of the next issues. Let me know whether we can merge :+1:

**Comment by ekoontz** [comment]
Looks good to me for merging!

**Pull request merged**
