### PR TITLE
use java8 (not java11) for runtime for JVM lambdas to avoid 'java.lan…

### PR DESCRIPTION
**Pull request by ekoontz**
…g.ExceptionInInitializerError'

Fix for https://github.com/FieryCod/holy-lambda/issues/26 
cc @burinc

### CODE REVIEW

**Comment by burinc** [comment]
@ekoontz 
Confirm that it works for me after this change.
Not sure why it fail with java11.

👍

**Comment by FieryCod** [comment]
@ekoontz, we should support java11. 
@burinc, please manually switch to java8.  We'll find out what causes this issue and notify you then.

**Comment by burinc** [comment]
@ekoontz 
It seems to be working properly with java 11 now.
Will close this issue.
Thanks

**Comment by ekoontz** [comment]
Closing this since it can be avoided by upgrading Clojure per https://github.com/FieryCod/holy-lambda/issues/26#issuecomment-812866420

**Comment by FieryCod** [comment]
Actually it's not upgrading. It's downgrading. I've created and issue on AWS SAM repo.

**Comment by ekoontz** [comment]
@FieryCod thanks, you're right, downgrading. Fixed the text in my previous comment accordingly.

**Pull request closed without merging**
